# Generated by Django 3.2.25 on 2024-08-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft_builder_user',
            name='profile_picture',
        ),
    ]
