# Generated by Django 3.2.25 on 2024-08-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
